/*******************************************************************************
 * This file is part of RedReader.
 *
 * RedReader is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * RedReader is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with RedReader.  If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************/

package org.quantumbadger.redreader.database

import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Room entity representing a subreddit for offline access.
 * Mirrors key fields from RedditSubreddit for caching and local lookup.
 */
@Entity(
    tableName = "subreddits",
    indices = [Index(value = ["name"], unique = true)]
)
data class SubredditEntity(
    @PrimaryKey val name: String,
    val displayName: String? = null,
    val displayNamePrecedence: Int? = null,
    val iconUrl: String? = null,
    val bannerUrl: String? = null,
    val description: String? = null,
    val subscribers: Long? = null,
    val createdUtc: Long? = null,
    val over18: Boolean? = null,
    val postingRestrictedToMods: Boolean? = null,
    val accountAgeSeconds: Long? = null,
    val quarantineDays: Long? = null,
    val subredditType: String? = null,
    val wikiEnabled: Boolean? = null,
    val wikiEditBans: Boolean? = null,
    val canMod: Boolean? = null,
    val userFlavorEnabled: Boolean? = null,
    val userCanLeave: Boolean? = null,
    val userIsBanned: Boolean? = null,
    val userIsMuted: Boolean? = null,
    val userFlairEnabledInNewPost: Boolean? = null,
    val userFlairEnabledInComment: Boolean? = null,
    val userFlairPosition: String? = null,
    val userFlairText: String? = null,
    val userFlairResourceId: String? = null,
    val userFlairBackgroundColor: String? = null,
    val userFlairTextColor: String? = null,
    val userFlairCssBackground: String? = null,
    val userFlairCssBackgroundDark: String? = null,
    val userFlairCssBackgroundLight: String? = null,
    val userFlairCssText: String? = null,
    val userFlairCssTextDark: String? = null,
    val userFlairCssTextLight: String? = null,
    val userFlairBackgroundColorHex: String? = null,
    val userFlairTextColorHex: String? = null,
    val userFlairBackgroundColorDark: String? = null,
    val userFlairTextColorDark: String? = null,
    val userFlairBackgroundColorLight: String? = null,
    val userFlairTextColorLight: String? = null,
    val userIsContributor: Boolean? = null,
    val userIsModerator: Boolean? = null,
    val userHasFollowed: Boolean? = null,
    val userCanLeaveSubreddit: Boolean? = null,
    val submissionTypeAllowed: String? = null,
    val userSubmitText: String? = null,
    val defaultSet: Boolean? = null,
    val headerHoverTextAuthor: String? = null,
    val headerHoverTextAuthorLink: String? = null,
    val headerHoverTextSelf: String? = null,
    val headerHoverTextSelfLink: String? = null,
    val mobileStyleOverrideUrl: String? = null,
    val originalContentTagEnabled: Boolean? = null,
    val showMedia: String? = null,
    val headerBannerUrl: String? = null,
    val keyColor: String? = null,
    val submissionType: String? = null,
    val communityIconUrl: String? = null,
    val allowImages: Boolean? = null,
    val title: String? = null,
    val url: String? = null,
    val lang: String? = null,
    val defaultLinkFlairTemplateId: String? = null,
    val defaultUserFlairTemplateId: String? = null,
    val restrictPostLength: Boolean? = null,
    val restrictImagePosting: Boolean? = null,
    val userIsPending: Boolean? = null,
    val userIsNoteBanned: Boolean? = null,
    val userIsNoteBannedGlobal: Boolean? = null,
    val userIsInWhitelist: Boolean? = null,
    val userIsInWhitelistGlobal: Boolean? = null,
    val userIsInShadowbanList: Boolean? = null,
    val userIsInShadowbanListGlobal: Boolean? = null,
    val userIsInBannedList: Boolean? = null,
    val userIsInBannedListGlobal: Boolean? = null,
    val userIsInContributorList: Boolean? = null,
    val userIsInContributorListGlobal: Boolean? = null,
    val userIsInModeratorList: Boolean? = null,
    val userIsInModeratorListGlobal: Boolean? = null,
    val userIsInAdminList: Boolean? = null,
    val userIsInAdminListGlobal: Boolean? = null,
    val userIsInFullModList: Boolean? = null,
    val userIsInFullModListGlobal: Boolean? = null,
    val userIsInReportedSpamList: Boolean? = null,
    val userIsInReportedSpamListGlobal: Boolean? = null,
    val userIsInIgnoredSpamList: Boolean? = null,
    val userIsInIgnoredSpamListGlobal: Boolean? = null,
    val userIsInUnapprovedList: Boolean? = null,
    val userIsInUnapprovedListGlobal: Boolean? = null,
    val userIsInApprovedList: Boolean? = null,
    val userIsInApprovedListGlobal: Boolean? = null,
    val userIsInPendingList: Boolean? = null,
    val userIsInPendingListGlobal: Boolean? = null,
    val userIsInMutedList: Boolean? = null,
    val userIsInMutedListGlobal: Boolean? = null,
    val userIsInUnmutedList: Boolean? = null,
    val userIsInUnmutedListGlobal: Boolean? = null,
    val userIsInBannedListForCommunity: Boolean? = null,
    val userIsInBannedListForCommunityGlobal: Boolean? = null,
    val userIsInMutedListForCommunity: Boolean? = null,
    val userIsInMutedListForCommunityGlobal: Boolean? = null,
    val userIsInUnbannedList: Boolean? = null,
    val userIsInUnbannedListGlobal: Boolean? = null,
    val userIsInUnmutedList: Boolean? = null,
    val userIsInUnmutedListGlobal: Boolean? = null,
    val userIsInWhitelistForCommunity: Boolean? = null,
    val userIsInWhitelistForCommunityGlobal: Boolean? = null,
    val userIsInShadowbanListForCommunity: Boolean? = null,
    val userIsInShadowbanListForCommunityGlobal: Boolean? = null,
    val userIsInBannedListForCommunity: Boolean? = null,
    val userIsInBannedListForCommunityGlobal: Boolean? = null,
    val userIsInContributorListForCommunity: Boolean? = null,
    val userIsInContributorListForCommunityGlobal: Boolean? = null,
    val userIsInModeratorListForCommunity: Boolean? = null,
    val userIsInModeratorListForCommunityGlobal: Boolean? = null,
    val userIsInAdminListForCommunity: Boolean? = null,
    val userIsInAdminListForCommunityGlobal: Boolean? = null,
    val userIsInFullModListForCommunity: Boolean? = null,
    val userIsInFullModListForCommunityGlobal: Boolean? = null,
    val userIsInReportedSpamListForCommunity: Boolean? = null,
    val userIsInReportedSpamListForCommunityGlobal: Boolean? = null,
    val userIsInIgnoredSpamListForCommunity: Boolean? = null,
    val userIsInIgnoredSpamListForCommunityGlobal: Boolean? = null,
    val userIsInUnapprovedListForCommunity: Boolean? = null,
    val userIsInUnapprovedListForCommunityGlobal: Boolean? = null,
    val userIsInApprovedListForCommunity: Boolean? = null,
    val userIsInApprovedListForCommunityGlobal: Boolean? = null,
    val userIsInPendingListForCommunity: Boolean? = null,
    val userIsInPendingListForCommunityGlobal: Boolean? = null,
    val userIsInMutedListForCommunity: Boolean? = null,
    val userIsInMutedListForCommunityGlobal: Boolean? = null,
    val userIsInUnmutedListForCommunity: Boolean? = null,
    val userIsInUnmutedListForCommunityGlobal: Boolean? = null,
    val hasFetched: Boolean? = null,
    val lastFetchTime: Long? = null,
    val fetchFailureCount: Int? = null
)
